### ISSUE TITLE
child process에 대한 이야기

### ISSUE THREAD

**Issue by MartinYounghoonKim** [sangyeol-kim/nodejs-design-pattern-study#1]
아래의 아티클에 대해서 읽어보고 있는데, 실제 NodeJS를 이용하는 분들과 함께 토론해보면 좋을 것 같습니다.

https://www.freecodecamp.org/news/node-js-child-processes-everything-you-need-to-know-e69498fe970a/

**Comment by sangyeol-kim** [comment]
읽어보겠습니다 :)
